name: Build and Deploy to GCP VM

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-bd8e23f4-e7fc-43d5-99e
  REGION: asia-southeast1
  REPO_NAME: cv-builder-repo
  IMAGE_NAME: rag-cv-builder

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          project_id: '${{ env.PROJECT_ID }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest"
          docker build -t $DOCKER_TAG -f docker/Dockerfile .
          docker push $DOCKER_TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/_work/rag-cv-builder
            
            gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
            
            docker compose -f docker-compose.prod.yml pull api
            docker compose -f docker-compose.prod.yml up -d
            
            docker image prune -f